
<?php

// Connect to the database
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "bus_registration";

$conn = new mysqli($servername, $username, $password, $dbname);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
?>

<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // extract form data
    $name = $_POST['name'];
    $surname = $_POST['surname'];
    $cellphone = $_POST['cellphone'];
    $email = $_POST['email'];

    // Generate autogenerated password 
    $generatedPassword = $name . $surname . '123@';

    // Save data to database
    $stmt = $conn->prepare("INSERT INTO parent (ParentName, ParentSurname, ParentCellNo, ParentEmail, ParentPassword) VALUES (?, ?, ?, ?, ?)");
    $stmt->bind_param("sssss", $name, $surname, $cellphone, $email, $generatedPassword);//this statement is used to pass variables

    if ($stmt->execute()) {
        // If data inserted successfully
        $stmt->close();
        
        // Send email notification to parent
        $to = $email;
        $subject = 'Registration Confirmation';
        $message = 'Thank you for registering. Your password is: ' . $generatedPassword;
        $headers = 'From: admin@impumelelo.high.school.co.za';

        if (mail($to, $subject, $message, $headers)) {
            header('Location: learner_registration.html'); // Redirect to learner registration page
            exit();
        } else {
            echo "Email sending failed.";
        }
    } else {
        // Error occurred
        echo "Error: " . $stmt->error;
    }
}
?>
